### ISSUE TITLE
Object fields initialization

### ISSUE THREAD

**Issue by charig** [charig/TruffleMATE#2]
Analyze if the initialization of Objects with nil in the OSM is blocking optimizations for primitive values. 
In case it is happening leave fields uninitialized until a conrete type is set.

**Comment by smarr** [comment]
Here a simple program that can be stepped through easily with as a BasicInterpreterTest, add the following to the array with tests: `{"ObjectFieldAccess",     "test",  4, Long.class },`

The test:

``` Smalltalk
ObjectFieldAccess = (
 | a |

 do = (
   a := 4.
   ^ a
 )
 ----
 test = (
  ^ ObjectFieldAccess new do.
 )
)
```

Beside the original issue, I note a couple of other things, that probably are problematic.
It is not clear that the `FieldWriteNode` still can be kept like that as it was for the SOM OM.
Not sure that the type specialization should be done on that level, may be, but not necessarily the way it is now. Does the OSM provide any nodes to do writes?

The next issue is the `UninitializedWriteFieldNode`. The method `writeAndRespecialize(.)` uses `obj.setField(fieldIndex, value);`. This is most likely another major issue, because the value is never stored as a primitive. `setField()` used to do the right thing. But, now it uses a generic store (`Property.set()` which does eventually `setGeneric()`, which forces the storage location to become an object location.

The result of that is that the OSM reserves a DualLocation, which is not actually checked for in the `writeAndRespecialize()` methods. So, it creates a `WriteObjectFieldNode`. And thereby it is certain that primitive values are never actually stored as primitives, but only as objects.

So, just by the current construction it does not work. This does not necessarily mean that it could not work even with initialization to nil. But, with the current implementation it stores all fields as objects.

**Comment by charig** [comment]
For the initialization i almost have a solution. Initialize all the fields with a DeclaredDualLocation with the nil object as the default value. I have a preliminary implementation almost working, will try to finish it tomorrow because there are some tests still failing.

Regarding the specialization nodes, well yes. I didn´t remove the node specializations from the standard implementation because i was not sure at the moment i started implementing this. 
Now i see two alternatives: 
i) Add one more case in the if to check for the actual type of the dual location. 
ii) Remove all the specialization nodes and leave the stuff to the dynamic object. I prefer this option but i am not sure if this will have an impact on efficiency.

What do you think?

**Comment by smarr** [comment]
I would go with something similar to pull request #3. The write node still needs to be adapted.
And then, I'd just remove the initialization code.
Instead, the read node should handle that the shape does not have the location. If it doesn't have the location, that's the hint that the field has not yet been set on that object. And, this can be cached, to return nil from the read node.

This approach would also mean that objects freely evolve in their shapes, and are not bound to the class anymore. This is probably a good thing with respect to layout support in the metaobject protocol. Not entirely sure yet.

Either way, if there would be a `Tuple` or `Pair` class or something similar, it would make sure it can be specialized independently of a calls and based on the various possible uses of those objects.

**Comment by charig** [comment]
I finally commit a workaround for the initialization.
Mainly all the fields now are implemented with a dual Location initialized with nil. 
This is because i based the implementation in the OSM shape object and it requires to install an storage location at initialization step. However i find the DeclaredDualLocation which i expect to be optimized by graal for the initialization of obejcts since it does not actually write the nil value in the field. However it remains the issue with the @Explodeloop.

Probably the code in the FieldAccessorNode can still be improved. Anyway, it would be good if we can compare SOM with and without the OSM with this new approach.

Have you forked from this repo meaning that you can just pull this commit or you would need a pull request?
