### ISSUE TITLE
Computing the receiver

### ISSUE THREAD

**Issue by charig** [charig/TruffleMATE#6]
At this moment the receiver of Message node is being calculated twice when there is no reflective redefinition for the lookup and the activation.

Essentially it is calculated first for doing all the mate tests to check if the operation is redefined in a metaobject. In case it is not, then the original wrapped message node is executed and it calculates its receiver again.

A solution would be to change the som message send nodes so they execute receiving the receiver as a parameter and then it would be calculated just once with the mate checks. 

Note: We must ensure that the execution of the receiver tree is optimized as usual.

**Comment by smarr** [comment]
Why are not all arguments first evaluated?

Why only the receiver?
If you would have all the Mate machinery only after the evaluation of all arguments, you would not have these issues.

The major question is, I guess, whether it makes sense to redefine the semantics of argument evaluation on this level. Is this even supported by the MOP?

**Comment by charig** [comment]
Well...I would like to start with these issue, but there are a couple of issues i am still not sure how to tackle.

i) When you suggest to first compute the arguments and then start the mate machinery you mean to change how Mate nodes are install or just leave the wrappers like this and call first an evaluateArguments() on each the wrapped node and then if metaobjects are not install do something like wrappedNode.executeEvaluated()?

ii) What do you mean with redefining the semantics of argument evaluation? At message send there is always a need to first compute the arguments starting to the receiver up to the last arguments. Why would Mate be changing this?

iii) Why you mean with supported by the MOP? There is an argumentReadNode. Ideally i would like to mateify this node too because Mate conceptually allows to redefine all the semantics of the interpreter and so it should allow to redefine every AST operation. But first i would like to measure performance with the current reifications (message and layout).

**Comment by smarr** [comment]
i) I am not sure whether that's the best way. Perhaps a more thorough refactoring would be better. I have somewhat similar functionality already in TruffleSOM. The `Eager(Unary|Binary|Ternary)PrimitiveNode` classes are built so that they first evaluate the arguments and then delegate execution to a wrapped node. They are meant to handle primitive operations, but allow to fallback to normal message sends in case this optimistic optimization failed.

This probably means changing a bit more about the MOP implementation. But, it seems to fix some of the issues currently observed, and the need to handle receiver and the rest of arguments differently.

ii & iii) In Smalltalk this is not a thing. And I do not propose to allow that. There are other ways. But, one could imagine the need for something like Lisp's macros, f-expressions, etc. Where one does not want the arguments to be evaluated, but only later decide how to handle them. I don't think this was ever meant to be part of the MOP. So, I would really not go into this direction. 

For the moment, my feeling is that the underlying issue of stability of the AST, and reevaluation of the receiver, are the highest priority issues, because we can't work around it for the Graal compilation. So, a refactoring to evaluate all arguments first, and then do all the MOP operations as part of `executeEvaluated()` seems to me as an important next step. For the moment, that's the only idea I got how to fix it.

**Comment by charig** [comment]
If stabilization is just an issue of avoiding having a node with two parents i will fix that easy just by removing the @child annotation in the mate receiver node and convert it to a reference.

Then for the refactoring i think i would also include the issue with the frame slot evaluation that is the other thing that is blocking optimizations and it also concerns probably argument evaluation... 

But before starting the refactoring i would like two things:

i) Devise a concrete plan/design.

ii) have concrete measurements of the actual implementation in an as efficient as possible version so we can compare the improvements of the refactoring. I would also like to measure the  `MateWithoutSpeculation` branch to make a comparison and test if making the things more `Truffle-Oriented` is paying something. 
Can you help me with this with the som evaluation infrastructure? Otherwise i can just run all the benchs and save the results.

**Comment by smarr** [comment]
Technically, just leaving out `@child` will not work, except the reference is never used for actual execution. But I understood it is used. How do you make sure that the two fields (the one with `@child` and the one without) are kept in sync? If the one without `@child` is used for execution, it will never stabilize, because, the node in that field is likely to be an uninitialized node, that then on each execution tries to specialize itself, but fails to actually store the new node anywhere.

If the frame-slot issue can be fixed with the same go, sure. But, it is less urgent, in the sense that it does not hinder compilation. It just makes everything very slow. But, the reuse of one node, or the failure to keep specialized nodes as just described, will cause the execution to never stabilize, which means, there is no 'steady state' to be measured.

The numbers you get for such executions are not really telling us anything.

I am also not sure what exactly your plan is with the 'having concrete measurements', i.e., ii).
Is that just to have a proper performance tracking during development? Sure, that's interesting and good engineering practice. From a scientific perspective however, it is not very relevant. I mean, sure, it would be interesting to have an experiment at the end that shows the impact of applying no optimizations at all, and applying all of them. However, I would rather do that after the fact, by removing/disabling optimizations. This here seems to me like fundamental structural things that need to be solved.

For the last point with the SOM infrastructure. Well, the current setup of http://som-speed.stefan-marr.de unfortunately does not seem to track the changes for the Mate branch. I am not sure why. It just doesn't display the data. The other thing is, there is already a lot of stuff on that Codespeed instance, and I would rather not add yet another set of experiments. Because it is already hard to keep things useful for myself. I think, it would be better just to setup another [codespeed](https://github.com/tobami/codespeed/) instance somewhere and collect the data for performance tracking there. I guess, we could do that on my server as well. But, would need to look into setting that up. And I haven't done that in a while.

Depending on what you want to do exactly with that data, there is also no way around keeping the proper data files ReBench produces. Those files should be the input for a proper analysis for a paper or so. The codespeed instance is really only useful for date to date development to have somewhat easy access to aggregated data and track performance relative to changes.

Another aspect, the actual execution of the benchmarks is also an issue. I currently use a benchmark server that is not publicly accessible. And, I unfortunately can't give you access to it, it isn't mine, I am just allowed to use it...

**Comment by charig** [comment]
I agree there is a problem with synchronization. However, the node converted to a reference is just used for evaluating the receiver. And the receiver should always be computed to the same value, no matter the specializations. Then what i would expect is the receiver evaluation not to be specialized but also not blocking the compilation of the whole method...

Regarding the measurement framework...Sure i do not want to put more load on your servers and neither make you lose time with cofigurations. I have never used codespeed. Perhaps you can just send me the config files you are using and some pointers to the apps, servers, etc. and i can see if i can config a server here.

Finally the most important thing. I would like to start tomorrow with the refactoring of this issue.
I agree that doing the mate tests after argument evaluation is the way to go. 
However i was thinking there are two ways of doing this:

i) Keep the actual model and make the ´mate node´ to call a method from the ´wrapped node´ like ´evaluateArguments()´. Afterwards do all the Mate test and in case there is no metaobject redefiniton call the ´wrapped node´ with an ´executeEvaluated()´. I would prefer this option since this way i do not have to change the som original nodes and can more or less easily keep updated when the original som changes. However i am not sure if this way of calling methods on the ´wrapped node´ is optimizable.

ii) Change the som nodes so after evaluating the arguments they call a ´mate node´ more or less the same way you do this wrapping in the ´eagerPrimitives´. This will be optimizable for sure but i will have to change the original som nodes. Perhaps i can subclass the som nodes and reimplement the ´executeEvaluated´ methods for calling mate but i am not sure how many type problems this will introduce...

What do you think?

**Comment by smarr** [comment]
WRT the receiver computation: your intuition is not correct. But, for another reason this might still work. Since you use the non-`@Child` node essentially only to get to the receiver node, it should be fine. So, this means, the non-`@Child` node is not used for execution, only for traversing the AST. The receiver node itself is still in a correct `@Child` node, and thus, specializations will be persisted in the AST. So, it should work. The problem with your understanding is that during specialization, when the node is supposed to be replaced, execution returns to the interpreter, and invalidates the corresponding native code. If this happens again and again, each compiled piece of native code is only ever execute once. And recompilation happens again and again.

For the codespeed instance, I can try to set something up. My concern was merely that I do want to have a separate instance. It also makes browsing data/results easier.

i) I think, SOM as it is won't change anymore. I do all my work in SOMns. So, I wouldn't worry about that. Better have something that is the simplest solution for your problem. I am not sure what exactly you propose here, but in general, the DSL already supports the classic evaluation model of first evaluating all subexpressions and than doing the node's semantic. And I think that's exactly what you need. The actual node semantic can include MOP tests and/or specializations. Not sure what the problem with optimizations should be?

ii) I think this would be the easiest way to go. Depending on the concrete experiments you want to do, you might use subclasses or just directly change the nodes, or have alternative nodes, which would probably be simpler.

**Comment by charig** [comment]
Great. Thanks for the feedback. 

Tomorrow i will start with the refactoring. i will ping when i have something concrete.

For the codespeed issue let me know if i can help. Again, if it will take much of your time with some help i may be able to setup an instance in my lab servers.

**Comment by charig** [comment]
With the last commit: https://github.com/charig/TruffleMATE/tree/2086d5747e9d9adc9d638bfa92557663010128ca
on the SOMwithTheOSM branch the refactoring is finished:
